apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-node-deployment
  labels:
    app1: kubernetes-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app1: kubernetes-node
  template:
    metadata:
      labels:
        app1: kubernetes-node
    spec:
      containers:
      - name: kubernetes-node
        image: kubernetes-node:v3 
        imagePullPolicy: IfNotPresent
        ports:
        - name: con-run-port
          containerPort: 9000
