apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-node
  name: kubernetes-node-deployment
spec:
  ports:
  - port: 4000
    targetPort: con-run-port
  selector:
    app: kubernetes-node
  type: LoadBalancer