---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Master template for all the cloud formaton template.

Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

  NodeImageId:
    Description: AMI id for the node instances.
    Type: AWS::EC2::Image::Id
    Default: ami-098fb7e9b507904e7

  NodeInstanceType:
    Description: EC2 instance type for the node instances
    Type: String
    Default: t2.small
    ConstraintDescription: Must be a valid EC2 instance type
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      
##################
  NodeAutoScalingGroupMinSize:
    Description: Minimum size of Node Group ASG.
    Type: Number
    Default: 1

  NodeAutoScalingGroupMaxSize:
    Description: Maximum size of Node Group ASG. Set to at least 1 greater than NodeAutoScalingGroupDesiredCapacity.
    Type: Number
    Default: 4

  NodeAutoScalingGroupDesiredCapacity:
    Description: Desired capacity of Node Group ASG.
    Type: Number
    Default: 3

  NodeVolumeSize:
    Description: Node volume size
    Type: Number
    Default: 20

  BootstrapArguments:
    Description: Arguments to pass to the bootstrap script. See files/bootstrap.sh in https://github.com/awslabs/amazon-eks-ami
    Type: String
    Default: ""
##################

  TemplateBucket:
    Type: String
    Default: eks-mritunjay-kumar
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Configuration
        Parameters:
          - TemplateBucket

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/eks-vpc.yml"
      Parameters:
        VpcBlock: 10.215.0.0/16
        Subnet01Block: 10.215.10.0/24
        Subnet02Block: 10.215.20.0/24
        Subnet03Block: 10.215.30.0/24
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/eks-cluster.yml"
      Parameters:
        ClusterName: !Sub eks-${AWS::StackName}
        ClusterVersion: "1.11"
        SubnetIds: !GetAtt VPC.Outputs.SubnetIds
        VpcId: !GetAtt VPC.Outputs.VpcId

  NodeGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/eks-nodegroup.yml"
      Parameters:
        KeyName: !Ref KeyName
        NodeImageId: !Ref NodeImageId
        NodeInstanceType: !Ref NodeInstanceType
        NodeAutoScalingGroupMinSize: !Ref NodeAutoScalingGroupMinSize
        NodeAutoScalingGroupMaxSize: !Ref NodeAutoScalingGroupMaxSize
        NodeAutoScalingGroupDesiredCapacity: !Ref NodeAutoScalingGroupDesiredCapacity
        NodeVolumeSize: !Ref NodeVolumeSize
        ClusterName: !Sub eks-${AWS::StackName}
        BootstrapArguments: !Ref BootstrapArguments
        NodeGroupName: !Sub NodeGroupName-${AWS::StackName}
        ClusterControlPlaneSecurityGroup: !GetAtt Cluster.Outputs.SecurityGroups
        VpcId: !GetAtt VPC.Outputs.VpcId
        Subnets: !GetAtt VPC.Outputs.SubnetIds
