---
# Deployment.


kind: Deployment
apiVersion: apps/v1
metadata:
  name: j-hello
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: j-hello
        image: janakiramm/j-hello
        ports:
        - name: nodejs-port
          containerPort: 3000

