---
# Step 6

kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000 # browser uses this port.
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer

