---
# Step 5.

kind: ReplicationController
apiVersion: v1
metadata:
  name: my-database-app
  labels:
    app: my-database-app
spec:
  replicas: 3
  selector:
    app: my-database-app
  template:
    metadata:
      labels:
        app: my-database-app
    spec:
      containers:
      - name: my-database-app
        image: ashupost/my-database-app:v1
        ports:
        - name: http-server
          containerPort: 3000

