---
# Step 6

kind: Service
apiVersion: v1
metadata:
  name: my-database-app
  labels:
    app: my-database-app
spec:
  ports:
  - port: 3000 # browser uses this port.
    targetPort: http-server
    nodePort: 32001
  selector:
    app: my-database-app
  type: NodePort

