apiVersion: apps/v1
kind: Deployment
metadata:
    name: secret-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      name: secret-storage
  template:
    metadata:
      labels:
        name: secret-storage
    spec:
      containers:
        - name: secret-storage
          image: ashupost/redis:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: my-port-name
              containerPort: 9000
          volumeMounts:
            - name: secret-volume
              mountPath: /my-secret-data # cat my-secret-data/username -> myusername
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-meta-name

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-meta-name
data:
  username: bXl1c2VybmFtZQ== # echo -n "myusername" | base64
  password: bXlwYXNzd29yZA== # echo -n "mypassword" | base64
