apiVersion: v1
kind: ReplicationController
metadata:
  name: red
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
        - name: red
          image: janakiram/color
          imagePullPolicy: IfNotPresent
          env:
            - name: "COLOR"
              value: "red"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: green
    spec:
      containers:
        - name: green
          image: janakiram/color
          imagePullPolicy: IfNotPresent
          env:
            - name: "COLOR"
              value: "green"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: blue
          image: janakiram/color
          imagePullPolicy: IfNotPresent
          env:
            - name: "COLOR"
              value: "blue"
          ports:
            - containerPort: 8080
