apiVersion: v1
kind: Service
metadata:
  name: red
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 31001
    name: http
  selector:
    color: red
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 31002
    name: http
  selector:
    color: green
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 31003
    name: http
  selector:
    color: blue
  type: NodePort