apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::418185438171:role/my-eks-NodeGroup-1AD5W39VKR28R-NodeInstanceRole-T0PAWDQAR3QY
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
