apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-app
spec:
  containers:
    - name: web-con-name
      image: ashupost/node-app:v1
#      imagePullPolicy: IfNotPresent
      ports:
        - name: web-con-port
          containerPort: 9000
          