apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: ashupost/node-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web-con-port
          containerPort: 9000